# Generated by Django 4.2.3 on 2024-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=50)),
                ('currentPrice', models.IntegerField()),
                ('oldPrice', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
