# Generated by Django 4.2.3 on 2024-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_alter_product_imageurl_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.TextField(),
        ),
    ]
